change firewall recent.time to string as per VyOS 1.4
vyos/vyos.vyos pull request #313
Opened 2023-04-11 21:42 UTC by athiedeilluminate

##### SUMMARY
Possibly Fixes #312

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Changing the type of a single variable.

2023-04-11 21:59 UTC, sever-sever commented
It's a moot point if you integrate it for the 1.4 rolling release; it will be broken for the stable 1.3 release, which still uses `int`
```
vyos@r1# set firewall name EXTERNAL-LOCAL rule 30 recent time 
Possible completions:
   <0-4294967295>
                Source addresses seen in the last N seconds
                
```
Are there any options to use some args for modules like version `1.3` or `1.4`, any other ideas?

2023-04-11 22:23 UTC, athiedeilluminate commented
I just started using this today, so I'm not very familiar with the codebase, but I can look into that. It would be nice to have the option. Or it could just be a freetext field?

2023-04-12 13:34 UTC, Qalthos requested changes
We technically only support vyos 1.1.x at the moment, but getting on to something newer is something that I have been wanting for a while, so if this works well enough to support newer versions in a transitional way, I'm all for it.

Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

2023-04-12 13:34 UTC, Qalthos commented on plugins/module_utils/network/vyos/argspec/firewall_rules/firewall_rules.py
> +                                                ]
You're missing a close brace here.
```suggestion
                                                ]
                                            }
```

2023-04-12 13:34 UTC, Qalthos commented on plugins/modules/vyos_firewall_rules.py
> +                    type: text ("second", "minute", or "hour")
```suggestion
                    - Source addresses seen in the last time period.
                    - Prior to 1.3, this is an integer representing a number of seconds.
                    - After 1.3, this is a string of either "second", "minute", or "hour".
                    type: raw
```

2023-04-12 13:51 UTC, sever-sever commented
> We technically only support vyos 1.1.x at the moment, but getting on to something newer is something that I have been wanting for a while, so if this works well enough to support newer versions in a transitional way, I'm all for it.

The thing is 1.1.x  EOL
1.2 is legacy LTS (could be downloaded here https://vyos.net/get/#1.2.9-S1)
1.3 LTS
1.4 Rolling/developing branch (https://vyos.net/get/nightly-builds/)

I guess it is better to open a new topic and discuss there capability and other options :)

2024-11-16 23:25 UTC, gaige commented
This should be fixed in #352 ; If you can pull from the current mainline branch, please confirm and close the PR.

2025-01-20 11:18 UTC, closed without merging