T6817 updates - fw_rules override fixes
vyos/vyos.vyos pull request #368
Opened 2024-12-18 06:31 UTC by omnom62

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

## Test results

- [ ] Sanity tests passed
- [ ] Unit tests passed

Tested against VyOS versions:

- 1.3.8
- 1.4-rolling-202201010100

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the ansible sanity and unit tests
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added unit tests to cover my changes
- [ ] I have added a file to `changelogs/fragments` to describe the changes

2024-12-27 10:42 UTC, gaige commented
You'll need to add the changelog file (note: you can't just amend another file, it needs a new file to pass the tests).

2025-01-14 10:01 UTC, gaige requested changes

2025-01-14 12:01 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/deleted_afi.yaml
> +        that: "{{ populate | symmetric_difference(result['before']) |length == 0 }}"
This was done to suppress:  [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{ rendered['commands'] |
symmetric_difference(result['rendered']) |length == 0 }}
Otherwise, I can reset it to the original format

2025-01-14 19:49 UTC, omnom62 commented on changelogs/fragments/firewall_rules.yml
> +  - fixed behavior for override and replaced states
Done

2025-01-14 20:04 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/deleted_afi.yaml
> +        that: "{{ populate | symmetric_difference(result['before']) |length == 0 }}"
restored

2025-01-14 20:05 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/overridden.yaml
> +      # ignore_errors: true
done

2025-01-14 20:08 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules14.py
it makes sense - will do

2025-01-14 20:09 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/vars/main.old
done

2025-01-14 20:10 UTC, omnom62 commented on changelogs/fragments/test_vyos_firewall_rules14.yml
> +  - Added test suite for firewall_rules for 1.4+
done

2025-01-14 20:14 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules14.py
> +            # "delete firewall ipv4 name V4-INGRESS rule 101 protocol",
done

2025-01-14 20:17 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +            # "delete firewall name V4-INGRESS rule 101 disable",
done

2025-01-14 20:17 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +            # "delete firewall name V4-INGRESS rule 101 log",
done

2025-01-14 20:19 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules14.py
> +    # def test_vyos_firewall_v4v6_rule_sets_rule_ovr_idem_01(self):
not anymore - was a temp comment to let other unit test runs w/o error

2025-01-14 20:21 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules.old
it was a temp backup - now removed. Do we want/have some .gitignore entry for this

2025-01-14 20:27 UTC, omnom62 commented on plugins/module_utils/network/vyos/config/firewall_rules/firewall_rules.py
> +        This function remove None (defaut)
This all has been replaced by the stock ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils.remove_empties, which does the same thing - I can analyse if the original dict is intact if it is worth it

2025-01-14 20:43 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules14.py
> +            # "delete firewall ipv4 name IF-TEST rule 10 inbound-interface name",
done

2025-01-16 20:59 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules14.py
This is mostly done - need to look into replaced idempotent unit tests for 1.4+ (actually, for all the data structures that include unsorted lists - e.g. packet_length_include, and the like) as this is now flapping (w and h comparison fails at times)

2025-01-20 21:07 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/_populate.yaml
> +      - set firewall group address-group 'inbound'
Done

2025-01-20 21:08 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/_remove_config.yaml
> +    lines:
Done

2025-01-20 21:34 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/tests/cli/parsed.yaml
> +        running_config: "{{ lookup('file', '_parsed_config_1_3.cfg') }}"
done

2025-01-20 23:09 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
It would be nice to have Puppet's deep_merge here when the vars of the same name get merged rather overwritten - I tried building common subsets in main.yaml while leaving only version specific ones in the pre-1.4 and the like, but it does not seem to work this way

2025-01-21 03:05 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
Anyway - this was resolved - I tried and D.R.Y the test data sets as much as possible  / practical

2025-01-23 09:47 UTC, gaige requested changes
Extremely close. There are a couple of yaml syntax changes and a couple of disabled tests we should look at and one new line of code that isn't being tested with either unit or integration tests.

Code coverage in the main modules changed here are over 80% and every new line (except the one above) is covered in either integration or unit, so that's great!

2025-01-23 09:47 UTC, gaige commented on plugins/module_utils/network/vyos/config/firewall_rules/firewall_rules.py
> +                commands.append(cmd + (" " + attr + " '" + w[attr] + "'"))
This line isn't reached in either the integration or unit tests. Probably easiest to add a unit test to make sure we exercise it.

2025-01-23 09:47 UTC, gaige commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
> +              state: "{{ state_dict}}"
Probably worth fixing the lint problem here, add a space after `state_dict`

2025-01-23 09:47 UTC, gaige commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
> +            state: "{{ state_dict}}"
Probably worth fixing the lint warning here, add a space after `state_dict`

2025-01-23 09:47 UTC, gaige commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +    # def test_vyos_firewall_rule_set_02_merged(self):
Why is this one commented out? If it's truly redundant, just remove. If not, then re-enable?

2025-01-23 09:47 UTC, gaige commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +    # def test_vyos_firewall_jump_rules_merged_01(self):
Why is this commented out? If it's truly redundant, go ahead and remove. If not, re-enable.

2025-01-23 19:37 UTC, omnom62 commented on changelogs/fragments/firewall_rules.yml
> +  - fixed behavior for override and replaced states
done

2025-01-23 19:38 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
> +              state: "{{ state_dict}}"
done

2025-01-23 19:39 UTC, omnom62 commented on tests/integration/targets/vyos_firewall_rules/vars/main.yaml
> +            state: "{{ state_dict}}"
done

2025-01-23 19:51 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +    # def test_vyos_firewall_rule_set_02_merged(self):
This one is redundant - identical unit test already exists under different name, therefore this one was commented and now removed

2025-01-23 19:53 UTC, omnom62 commented on tests/unit/modules/network/vyos/test_vyos_firewall_rules13.py
> +    # def test_vyos_firewall_jump_rules_merged_01(self):
Don't remember why this one was commented, so I re-enabled and tested

2025-01-23 20:39 UTC, omnom62 commented on plugins/module_utils/network/vyos/config/firewall_rules/firewall_rules.py
> +                commands.append(cmd + (" " + attr + " '" + w[attr] + "'"))
I added 2 tests to add and replace the log for 1.3 and 1.4
There were also already existing tests in repl_idem

2025-01-24 03:04 UTC, gaige approved these changes
LGTM

2025-01-25 11:10 UTC, andamasov approved these changes
Good to go

2025-01-25 11:38 UTC, merged